format = """
[â”Œâ”€](#fabd2f)$directory$git_branch$git_status
[â””â”€>](#fabd2f) """

[directory]
style = "#fabd2f"
truncation_length = 4
truncate_to_repo = true
fish_style_pwd_dir_length = 3

[directory.substitutions]
"Documents" = " ó°§® "
"Music" = " ï€ "
"Movies" = " ó°¿ "
"Pictures" =  " ï€¾"
"Sources" = " ï„¡ "
"Downloads" = " ï€™ "
"~" = " ğŸ‘¾"
"/" = " â”€|"

[line_break]
disabled = true

[git_branch]
style = "#d3869b"
disabled = false
symbol = "î¬€ "
truncation_length = 5
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_commit]
disabled = false
commit_hash_length = 1

[git_status]
disabled = false
style = "#fe8019"
stashed = "ï€œ ${count} "
ahead = "ó°™ ${count} "
behind = "ó°’ ${count} "
diverged = "ó°µ‰ ${ahead_count} ${behind_count} "
conflicted = "ï€¤ ${count} "
deleted = "ï’ ${count} "
renamed = "ï„­ ${count} "
modified = "ï„ ${count} "
staged = "ï‡™ ${count} "
untracked = "ó±…˜ ${count}"

[character]
success_symbol = "[â¯](#b8bb26)"
error_symbol = "[âœ–](#fb4934)"
